name: 🤝 Contributor Access Request
description: Request to become a contributor for reviewing AI-generated code and prompts
title: "Contributor Request: [Your GitHub Username]"
labels: ["contributor-request", "review-access"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🤝 Contributor Access Request

        Thank you for your interest in becoming a contributor! We're looking for reviewers to help with AI-generated code and prompts.

  - type: input
    id: github-username
    attributes:
      label: 👤 GitHub Username
      description: Your GitHub username
      placeholder: "@your-username"
    validations:
      required: true

  - type: checkboxes
    id: ai-experience
    attributes:
      label: 🤖 Your Experience with AI Development Tools
      description: Check all that apply
      options:
        - label: "GitHub Copilot"
        - label: "ChatGPT/GPT models for coding"
        - label: "Other AI coding assistants"
        - label: "Prompt engineering for code generation"
        - label: "AI-powered testing and validation"

  - type: textarea
    id: other-ai-experience
    attributes:
      label: Other AI Development Experience
      description: Describe any other relevant AI development experience
      placeholder: Specify other AI tools or experience you have

  - type: checkboxes
    id: contribution-areas
    attributes:
      label: 🎯 Areas Where You'd Like to Help
      description: Check all areas of interest
      options:
        - label: "**Prompt Review**: Evaluating and improving AI prompts for feature implementation"
        - label: "**Code Quality Assurance**: Reviewing AI-generated code for best practices"
        - label: "**Testing**: Validating that AI implementations meet acceptance criteria"
        - label: "**Feature Prioritization**: Helping decide which features to implement"
        - label: "**Documentation**: Improving project documentation and guides"
        - label: "**UI/UX Review**: Ensuring user interface improvements are effective"
        - label: "**Schema Evolution**: Helping improve the resource classification system"
        - label: "**Content Curation**: Reviewing and suggesting AI development resources"
        - label: "**Automation Enhancement**: Improving AI workflows and processes"

  - type: textarea
    id: motivation
    attributes:
      label: 🔍 Your Interest in This Project
      description: Why are you interested in contributing to AI Practitioner Resources?
      placeholder: Explain your motivation, what draws you to this project, and how you see yourself contributing to the AI-first development approach
    validations:
      required: true

  - type: textarea
    id: technical-skills
    attributes:
      label: 🛠️ Relevant Skills & Experience
      description: Describe your technical background
      placeholder: |
        **Programming Languages**: [List languages you're comfortable with]
        **Web Technologies**: [HTML, CSS, JavaScript, etc.]
        **AI/ML Experience**: [Any machine learning or AI model experience]
        **Development Tools**: [Git, testing frameworks, CI/CD, etc.]
        **Domain Knowledge**: [AI development practices, software engineering, etc.]

  - type: textarea
    id: previous-contributions
    attributes:
      label: 📈 Previous Contributions
      description: Link to notable contributions or projects
      placeholder: |
        **Open Source Projects**: [Link to notable contributions or projects]
        **AI-Related Work**: [Any AI development or prompt engineering experience]
        **Code Review Experience**: [Experience reviewing code or managing projects]

  - type: checkboxes
    id: contribution-goals
    attributes:
      label: 🎯 Contribution Goals
      description: What would you like to achieve as a contributor?
      options:
        - label: "Help improve the quality of AI-generated implementations"
        - label: "Contribute to advancing AI-first development practices"
        - label: "Learn more about prompt engineering for software development"
        - label: "Support the community of AI-assisted developers"
        - label: "Help establish best practices for human-AI collaboration"

  - type: textarea
    id: other-goals
    attributes:
      label: Other Goals
      description: Any other goals you'd like to achieve
      placeholder: Specify any other contribution goals

  - type: dropdown
    id: time-commitment
    attributes:
      label: 📅 Time Commitment
      description: How much time can you realistically contribute?
      options:
        - A few hours per week
        - Several hours per week
        - A few hours per month
        - Flexible based on availability
        - Other (please specify in additional info)
    validations:
      required: true

  - type: checkboxes
    id: understanding
    attributes:
      label: 🚀 Getting Started
      description: If accepted as a contributor, I understand that I will
      options:
        - label: "Review AI-generated prompts and code implementations"
        - label: "Provide constructive feedback on feature implementations"
        - label: "Help maintain code quality standards"
        - label: "Contribute to the project's AI-first development philosophy"
        - label: "Follow the project's contribution guidelines and code of conduct"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 📞 Additional Information
      description: Anything else you'd like to share
      placeholder: Include any additional context, questions, or information that would help with your contributor request

  - type: markdown
    attributes:
      value: |
        ---

        **Thank you for your interest in contributing to AI Practitioner Resources! This project serves as an experiment in AI-first development, and your contributions help us explore the future of human-AI collaboration in software development.**
