name: 🐛 Bug Report
description: Report a bug or issue with the AI Practitioner Resources site or tools
title: "[BUG] [Brief Description]"
labels: ["bug", "triage-needed"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        
        Thanks for taking the time to report a bug! This helps us improve the AI Practitioner Resources project.

  - type: textarea
    id: bug-description
    attributes:
      label: 🔍 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened vs what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste image URLs

  - type: dropdown
    id: component
    attributes:
      label: 🎯 Component
      description: Which part of the project is affected?
      options:
        - Web Interface (index.html)
        - Resource Data (JSON)
        - Automation Scripts
        - Documentation
        - GitHub Templates
        - Other (please specify below)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🌐 Environment
      description: Tell us about your environment
      placeholder: |
        **Browser**: [e.g. Chrome 118, Firefox 119, Safari 17]
        **Operating System**: [e.g. Windows 11, macOS 14, Ubuntu 22.04]
        **Device**: [e.g. Desktop, Mobile, Tablet]
        **Screen Resolution**: [if relevant]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📚 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful

  - type: markdown
    attributes:
      value: |
        ---
        
        **Note**: If this bug affects the AI generation or automation processes, please include details about the specific prompt or automation step that failed.